### ISSUE TITLE
Two active forks of Exceptional plugin

### ISSUE THREAD

**Issue by ulex** [RobertWeinmeister/ExceptionalReSharper#5]
There are two active forks of the original Exceptional plugin pushed to JetBrains Marketplace
https://plugins.jetbrains.com/plugin/19461-exceptional-continued/
https://github.com/RobertWeinmeister/ExceptionalReSharper
by @RobertWeinmeister 

and 
https://plugins.jetbrains.com/plugin/14928-exceptional-by-mf
https://github.com/hhu-mahmoud/ExceptionalReSharper
by @hhu-mahmoud

It leads to an installation error, when both of these plugins are selected.

At the moment I am trying to find right way to resolve this issue. 
@RobertWeinmeister is there are any changes in the feature set comparing to the fork of @hhu-mahmoud?

Because of the installation error we need to have only one version of the plugin in the Marketplace and unlist the other one.
Please let us know as soon as possible about the differences between the versions.

**Comment by RobertWeinmeister** [comment]
What is the problem with two forks at the same time? They have different names, or?

https://github.com/hhu-mahmoud/ExceptionalReSharper was abandoned for some time so I created this one. At the moment it has one additional functionality, it allows to ignore certain namespaces.

Is there a way to keep both on the marketplace?

**Comment by ulex** [comment]
@RobertWeinmeister thanks you for quick response.
There are no problem with the two forks, there is problem with two plugins with the same dll name in the JetBrains Marketplace.
As I mentioned above, it leads to errors because these plugins cannot be installed simultaneously. Due to plugin's installation model installer attempt to copy two dll with the same name into the same directory.

> was abandoned for some time so I created this one

Did you try to contact the maintainer before creating another fork?

**Comment by hhu-mahmoud** [comment]
Hi I think there is no problem with 2 forks at the same time and also on the marketplace.

I'm not sure with 2 installs, cus the last instal will overwrite the first one. I think! 

Thank you @RobertWeinmeister to support the extension. I really abandoned my fork for some time, cus I was too busy to update it. Anyway I do at the moment only the neccessry updates to let the extension works but I don't add the moment any features or changes!

**Comment by hhu-mahmoud** [comment]
If anyone interested in the work on the extension with me .. it will be my pleasure :)
Just tell me then I will add you!

**Comment by RobertWeinmeister** [comment]
My priority was not to fork the plugin, I wanted to get it working again. I contacted @hhu-mahmoud back then and did not get a response, so I set it up myself. I do not mind merging them again or something similar.

**Comment by hhu-mahmoud** [comment]
@RobertWeinmeister  Sorry I didn't receive any message from you.
After I saw your comment on one Issue I updated it at the next day :) 

![grafik](https://github.com/RobertWeinmeister/ExceptionalReSharper/assets/32834850/15f3be1b-54e7-42f0-8ddb-c721997efe5d)

I added you to my repo.

**Comment by ulex** [comment]
@hhu-mahmoud thanks for joining the discussion and clarifying the situation!

> I'm not sure with 2 installs, cus the last instal will overwrite the first one. I think!

Unfortunately, It won't. Installation doesn't work that way. We are treating each plugin equal and the installer will just fail because it cannot select one dll from many possibilities. We do consider plugins equal to the our products as well, so this check ensures that, for example, there is no dll with the same name from ReSharper and dotTrace, which are developed by different team, but share the integration into Visual Studio (and the installation folder)

This is real issue, because we are receiving customer requests regarding failed installation.

There is also another way to resolve this issue and having two active forks: rename dll in one of the forks and ensure that ReSharper isn't broken then two plugins are installed. But this solution far from ideal.
